### ISSUE TITLE
System positioning

### ISSUE THREAD

**Issue by HelliceSaouli** [GGEMS/ggems#22]
Hello Didier I hope you are doing fine Inchallah.

So I'm trying to replicate a Dosimetry simulation (see the figure attached) using GGEMS since it is the fast MC that exist so far (nice work). however I'm straggling to figure out how to position my source.
![example](https://github.com/GGEMS/ggems/assets/10406314/eb2487ed-9356-46ee-9874-5a1512c51a45)

So according to the simulation i was trying to replicate they positioned the source at x= -50, y=70 and z = -10 all in mm the angles are (14.0, 14.0) in degree and the beam aperture is 10.0 degree. I used this information as followed in GGEMS:

`point_source = GGEMSXRaySource('point_source')`
 `point_source.set_source_particle_type('gamma')`
 `point_source.set_number_of_particles(number_of_particles)`
 `point_source.set_position(-50.0, 70.0, -10.0, 'mm')`
 `point_source.set_rotation(14.0, 0.0, 14.0, 'deg')`
 `point_source.set_beam_aperture(10.0, 'deg')`
 `point_source.set_focal_spot_size(0.3, 0.5, 0.0, 'mm')`
 `point_source.set_monoenergy(90, 'keV')`
and this is what i got : 
![image](https://github.com/GGEMS/ggems/assets/10406314/eac4a7dd-c9a0-4b71-8ccf-a55a14286dc0)

It is totally different, the volume i have is practically the same as their in term  of size 52  * 52 * 17 cm. I wonder how the positioning the sources should be done. also looked into the code i found "set_global_system_position"  according to the name it should offset the detector and the source in the global world coordinate but looking to the implementation it offset only the detector.
your help will be appreciated.

best regards
Abdelhak

**Comment by didierbenoit** [comment]
Hi Abdelhak,

I'm doing very well and I hope everything is going well with you too. I just checked the angles using the example 4 included in GGEMS for dosimetry. In the documentation, the rotation angles concern the axes in red (on the figure at the address https://doc.ggems.fr/v1.2/sources.html). I presume your patient is in the XY plane. Rotation in X will have no effect since photons are emitted along X by default. So, only angles in Y and Z will be useful for you. I'm sending you images. The first image has the parameter 'point_source.set_rotation(0.0, 0.0, 0.0, 'deg')'. The second image has the parameter 'point_source.set_rotation(0.0, 0.0, 25.0, 'deg')'. And the last images have the parameter 'point_source.set_rotation(0.0, 25.0, 0.0, 'deg')', in the XY plane and the XZ plane (the rotation in Y is more visible). In your case, your parameters should be 'point_source.set_rotation(0.0, 14.0, 14.0, 'deg')'.
![Y_0_degree_Z_0_degree](https://github.com/GGEMS/ggems/assets/83984121/5c06be25-c754-48d7-8ca4-d54bc4e50af5)
![Y_0_degree_Z_45_degree](https://github.com/GGEMS/ggems/assets/83984121/8e5b7345-7247-4906-b095-8d1809ff60c8)
![Y_25_degree_Z_0_degree_XYplane_fig1](https://github.com/GGEMS/ggems/assets/83984121/fc06910a-8a7a-4f24-86e5-5f4784a73779)
![Y_25_degree_Z_0_degree_XZplane_fig2](https://github.com/GGEMS/ggems/assets/83984121/5bac4bb3-f131-46c4-9aab-076ca207d626)


I hope that helps.
Kind regards
Didier

**Comment by HelliceSaouli** [comment]
Thanks a lot dear friend.  also I see you add OpenGL visualization to GGEMS, great job from the wizard of LaTIM x') btw can we visualize the MHD directly via GGEMS  now ?

**Comment by didierbenoit** [comment]
In example 6 of GGEMS you can see how we can visualize an MHD volume in GGEMS. To avoid memory problems, only an X, Y and Z section is displayed. The visualization in GGEMS is not perfect, and I'm working on visualizing a volume built with meshes and navigation of particles inside it. I managed to navigate with meshes and OpenCL I'm implementing in GGEMS
