### ISSUE TITLE
2080ti Bad Performance

### ISSUE THREAD

**Issue by Yao1993** [GGEMS/ggems#6]
I run the example 5_World_Tracking using the following command.
```
python world_tracking.py -n 10000000
```
The elpased times are shown below.
| Platform| Elapsed Time/s |
| ----------- | ----------- |
| 2080ti(Linux)        | 53|
| 2080ti(Windows)  | 48|
| 1060(Linux)           | 28|

It is very strange that 1060 run faster than 2080ti.

[2080ti_windows.log](https://github.com/GGEMS/ggems/files/7064177/2080ti_windows.log)
[2080ti_linux.log](https://github.com/GGEMS/ggems/files/7064197/2080ti_linux.log)
[1060.log](https://github.com/GGEMS/ggems/files/7064180/1060.log)

**Comment by didierbenoit** [comment]
Hi,
Yes it's strange, the problem is in GGEMSWorld::Tracking kernel. I did not optimized the algorithm (a simple DDA for projection) for GPU architecture, and surely something is not correct. Surely the cores are not used in an optimal way. I will check that. For the other kernels 2080Ti is faster than 1060, this case in normal :-)
Thank you for your return
Kind regards
Didier
